tls:
  certificates:
    - certFile: /certs/telos.crt
      keyFile: /certs/telos.key
  stores:
    default:
      defaultCertificate:
        certFile: /certs/telos.crt
        keyFile: /certs/telos.key
