tcp:
  routers:
    turn-tls:
      entryPoints:
        - turn
      rule: "HostSNI(`*`)"
      tls: {}
      service: turn-livekit
  services:
    turn-livekit:
      loadBalancer:
        servers:
          - address: "livekit:5349"
